# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-24 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanhosts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostloginifo',
            name='host_type',
            field=models.CharField(default='', max_length=256, null=True, verbose_name='虚拟机上宿主机的类型'),
        ),
        migrations.AlterField(
            model_name='hostloginifo',
            name='hostname',
            field=models.CharField(default='', max_length=256, null=True, verbose_name='操作系统主机名'),
        ),
        migrations.AlterField(
            model_name='hostloginifo',
            name='mac_address',
            field=models.CharField(default='', max_length=512, verbose_name='mac地址列表'),
        ),
        migrations.AlterField(
            model_name='hostloginifo',
            name='mathine_type',
            field=models.CharField(default='', max_length=256, verbose_name='机器的类型 1=物理服务器,2=虚拟资产,3=网络设备 0=其他类型(未知)'),
        ),
        migrations.AlterField(
            model_name='hostloginifo',
            name='rsa_pass',
            field=models.CharField(default='', max_length=64, null=True, verbose_name='私钥的秘药'),
        ),
        migrations.AlterField(
            model_name='hostloginifo',
            name='sn',
            field=models.CharField(default='', max_length=256, verbose_name='SN－主机的唯一标示'),
        ),
        migrations.AlterField(
            model_name='hostloginifo',
            name='sn_key',
            field=models.CharField(default='', max_length=256, verbose_name='唯一设备ID'),
        ),
        migrations.AlterField(
            model_name='hostloginifo',
            name='ssh_passwd',
            field=models.CharField(default='', max_length=64, null=True, verbose_name='ssh登录的用户'),
        ),
        migrations.AlterField(
            model_name='hostloginifo',
            name='ssh_rsa',
            field=models.CharField(default='', max_length=64, null=True, verbose_name='登录使用的私钥'),
        ),
        migrations.AlterField(
            model_name='hostloginifo',
            name='system_ver',
            field=models.CharField(default='', max_length=256, null=True, verbose_name='操作系统版本'),
        ),
    ]
