# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-24 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machineoperationsinfo',
            name='operation',
            field=models.TextField(choices=[(0, '增加'), (1, '删除'), (2, '修改')], default='', verbose_name='操作内容'),
        ),
        migrations.AlterField(
            model_name='machineoperationsinfo',
            name='person',
            field=models.CharField(default='', max_length=20, verbose_name='操作人用户名'),
        ),
        migrations.AlterField(
            model_name='machineoperationsinfo',
            name='remark',
            field=models.TextField(default='', verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='machineoperationsinfo',
            name='state',
            field=models.IntegerField(choices=[(0, '已报废'), (1, '测试使用'), (2, '线上运行'), (3, '下线')], default=2, verbose_name='设备使用状态'),
        ),
    ]
